import type { NextPage } from 'next'
import Head from 'next/head'
import { GetStaticProps } from 'next'
import { ArticleFeed, ArticleEntry } from '../components/feed/articleEntry'

type StaticProps = {
  articles: ArticleFeed[]
}

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch('http://localhost:8080/api/posts/feed?page=1')
  return {
    props: {
      articles: await res.json()
    },
  }
}

const Home: NextPage<StaticProps> = (props) => {
  return (
    <div>
      <Head>
        <title>Monomio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {props.articles.map(a => <ArticleEntry key={a.id} {...a} /> )}
    </div>
  )
}

export default Home
