import type { NextPage } from 'next'
import Head from 'next/head'
import { GetStaticProps } from 'next'
import { ArticleEntry } from '../components/feed/articleEntry'
import { getArticlePage } from '../lib/articles'
import type { ArticleFeed } from '../lib/types'
import Layout from '../components/layout'
import { Title, Container, Box } from '../components/styled'

type StaticProps = {
  articles: ArticleFeed[]
}

export const getStaticProps: GetStaticProps = async () => {
  const articles = await getArticlePage(1)
  return {
    props: {articles},
  }
}

const Home: NextPage<StaticProps> = (props) => {
  return (
    <Layout>
      <Head>
        <title>Monomio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Container padding='sm'>
        <Title order='2'>Resent Posts</Title>
      </Container>
      {props.articles.map(a => <ArticleEntry key={a.article.id} {...a} /> )}
      <Box css={{ padding: '5em'}}></Box>
    </Layout>
  )
}

export default Home
